### ISSUE TITLE
直连时，什么时候切换IP？

### ISSUE THREAD

**Issue by kzhiquan** [kohn/HttpProxyMiddleware#1]
看了源码，一直好奇，代理时，什么时候切换IP，尤其是当直连时，遇到服务器返回302 或者 403时， 
貌似在parse中抛出异常，在process_exception中也捕获不了，想让它切换IP，希望能明示。

**Comment by kohn** [comment]
需要切换IP时, yield一个新的request, req.meta["change_proxy"]=True即可. 至于是什么时候需要切换, 这个要看你的项目需要. 比如我看你的描述, 可能可以在parse中检查状态码, 发现302或者403时就yield request.

另外这份代码是我从一个项目中直接抽出来的, 封装的不是很好, 没想到还真有人用..稍后我会把最新的代码封装一下更新上来.
