### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by zymtech** [kohn/HttpProxyMiddleware#3]
HttpProxyMiddleware中request.meta["proxy_index"]会报错，KeyError：‘proxy_index'.

**Comment by kohn** [comment]
能提供更详细的信息吗? 光这些也不知道是哪一行的request.meta["proxy_index"].

出现这个错误应该是在使用request.meta["proxy_index"]之前没有经历set_proxy这一步, 或者在别的某个地方被你删了这个key. 

如果是在process_request函数里的错误的话, 可能是你使用错了...在爬虫一启动产生request的时候就被你设置了request.meta["change_proxy"]=True. 这个key是要在你parse的时候发现ip被ban了的时候才设置的.

**Comment by zymtech** [comment]
对的，是我使用错了，刚才想测一下能不能用，正常返回200的时候就把request.meta["change_proxy"]设置为了True。 多谢解答~
