### ISSUE TITLE
代码有句有点想不明白

### ISSUE THREAD

**Issue by findsomeoneyys** [kohn/HttpProxyMiddleware#4]
```
def process_request(self, request, spider):
"""
将request设置为使用代理
"""
if self.proxy_index > 0 and datetime.now() > (self.last_no_proxy_time + timedelta(minutes=self.recover_interval)):
logger.info("After %d minutes later, recover from using proxy" % self.recover_interval)
self.last_no_proxy_time = datetime.now()
self.proxy_index = 0
request.meta["dont_redirect"] = True
```

博主我想问下这段代码中self.proxy_index = 0是什么意思呢?如果是将request设置为使用代理的话,设置self.proxy_index = 0,不就是使用零号代理(无代理)了吗?

**Comment by kohn** [comment]
这个是一个优化, 如果已经20分钟没有用过0号代理, 就切换到0号代理. 因为用代理影响速度, 而0号代理休息了20分钟, 可能已经可以继续爬了.

这个20定义在**init**函数中的self.recover_interval, 可以根据具体爬的网站的不同进行设置. 比如有些网站一封就封一小时, 那这个recover_interval就最好设置为60.

**Comment by findsomeoneyys** [comment]
可能我是被logger.info("After %d minutes later, recover from using proxy" % self.recover_interval)误导了
 recover from using proxy 不是恢复使用代理的意思吗? 所以我就不明白为什么又恢复使用代理又设置回无代理
另外我在学scrapy中还有一点困惑,如果方便不知道能否指点一下

**Comment by kohn** [comment]
recover from表示从使用代理的情况中恢复出来...也就是不再使用..

scrapy我也没怎么用过, 写这个中间件其实和使用scrapy并没多大关系...

**Comment by findsomeoneyys** [comment]
明白了!谢谢!
