### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by fyzhang** [kohn/HttpProxyMiddleware#6]
我使用上面的代理去抓取点评的页面，运行几分钟后发生错误<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly，试过几次都是报同样的错误，所以想问下是代理IP不行吗？还是。。。

**Comment by kohn** [comment]
是代理有问题, 需要通过设置meta要求HttpProxyMiddleware切换下一个代理
